[build]
  command = "npm run build"      
  publish = "dist"               

[context.production]
  branch = "develop"             

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
